version: '3.8'

services:
  simplify-app:
    image: ghcr.io/zein-spectre/project-simplify-library-web:latest
    container_name: simplify-library-web
    restart: unless-stopped
    ports:
      - "2002:3000"
    environment:
      # BlockSuite Editor URL (menggunakan IP lokal CasaOS sesuai dengan port BlockSuite)
      - NEXT_PUBLIC_BLOCKSUITE_URL=http://192.168.110.124:2003
      
      # Appwrite Configuration (Ambil dari .env.local Anda)
      - NEXT_PUBLIC_APPWRITE_ENDPOINT=https://appwrite.geladisalam.my.id
      - NEXT_PUBLIC_APPWRITE_PROJECT_ID=simplify-library-3
      - APPWRITE_API_KEY=78fd3f6c3d92cb3416a4605ab957e6c2dab62f7483ba8a89a7b8b31dfdc70b6efe18a523eff06dceeff136c9d2706e5cee0c2fd69e92a5c1f8fd158af2f511aac76391414a54134350f70057d69efdca1ad7bd958c933d8e08e27f315c867730a8e8c0c75799b53b5e5e626176498e349a84199a86eaa114422ea85d7978ecce
      
      # Database & Collections
      - NEXT_PUBLIC_APPWRITE_DATABASE_ID=simplify-db
      - NEXT_PUBLIC_APPWRITE_BOOKS_COLLECTION_ID=books
      - NEXT_PUBLIC_APPWRITE_CHAPTERS_COLLECTION_ID=chapters
      - NEXT_PUBLIC_APPWRITE_SUBCHAPTERS_COLLECTION_ID=sub_chapters
      - NEXT_PUBLIC_APPWRITE_CATEGORIES_COLLECTION_ID=categories
      
      # Storage
      - NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID=simplify-covers
      
      # Bookmarks
      - NEXT_PUBLIC_APPWRITE_BOOKMARKS_COLLECTION_ID=bookmarks
      
      # Progress & Feedback
      - NEXT_PUBLIC_APPWRITE_USER_PROGRESS_COLLECTION_ID=user_progress
      - NEXT_PUBLIC_APPWRITE_FEEDBACKS_COLLECTION_ID=feedbacks

  blocksuite-editor:
    image: zeinspectre/simplify-library-editor:latest
    container_name: simplify-library-editor
    restart: unless-stopped
    ports:
      - "2003:80"
