server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;

        # Izinkan iframe dari Next.js (port 2002) dan dev ports
        add_header Content-Security-Policy "frame-ancestors 'self' http://localhost:2002 http://localhost:3000 http://localhost:3001 http://localhost:5173 http://192.168.110.124:2002" always;
        add_header X-Frame-Options "" always;
        add_header Access-Control-Allow-Origin "*" always;
    }
}
